name: actions_python_coveralls
description: A Github action for building a python package and publishing to pypi
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  pypi_username:
    description: "pypi username"
    required: true
    type: string
  pypi_password:
    description: "pypi password"
    required: true
    type: string
  pip_install_command: 
    description: "command used to install python dependancies"
    required: false
    type: string
    default: "pip install build setuptools setuptools_scm wheel twine"
  python_version:
    description: "version of python to run action with"
    required: false
    type: string
    default: "3.x"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: "Setup Python ${{ inputs.python_version }}"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: "Show Python Version"
      run: python --version
      shell: bash

    - name: "Install Python Dependencies"
      run: |
        python -m pip install --upgrade pip
        ${{ inputs.pip_install_command }}
      shell: bash
   
    - name: "Build and Publish"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TWINE_USERNAME: ${{ inputs.pypi_username }}
        TWINE_PASSWORD: ${{ inputs.pypi_password }}
      run: |
        python -m build
        twine upload dist/*
